# Languages for the UI


DIC = {
    "cz": {
        "open_file": "Otevřít soubor (otevře se v LandXML okně)",
        "exit": "&Ukončit",
        "settings": "&Nastavení",
        "language": "&Jazyk",
        "file": "&Soubor",
        "color_mode": "Motiv",
        "light": "Světlý",
        "dark": "Tmavý",
        "system": "Systémový",
        "raw_data": "Surová data",
        "parsed_data": "Zpracovaná data",
        "open_parse_landxml": "Otevřít a zpracovat &LandXML",
        "open_parse_xmlttp": "Otevřít a zpracovat XML &TTP",
        "cant_cant-def": "převýšení / nedostatek převýšení [mm]",
        "cant": "převýšení [mm]",
        "station": "staničení [km]",
        "speed_lim": "nejvyšší povolená rychlost [km/h]",
        "app_title": "COYPU - Clever Optimizer for Yielding of Potential and Utilization",
        "error": "Chyba",
        "no_file": "Nebyl vybrán žádný soubor nebo došlo k chybě při čtení souboru.",
        "clean": "&Vyčistit",
        "cleanTTP": "Vyčistit &TTP data",
        "cleanLandXML": "Vyčistit &LandXML data",
        "cleanAll": "Vyčistit &vše",
         "radius": "poloměr oblouku [m]",
         "curvature": "křivost [1/m]",
         "elevation": "výška [m]",
         "select_sections_for_ttp_title": "Vyberte úsek",
         "select_sections_for_ttp_description": "Vyberte úseky, které chcete zahrnout do TTP.",
         "crop_to_landxml": "Oříznout na rozsah LandXML dat",
         "unknown_xml_file": "Neznámý formát XML souboru. Očekává se LandXML nebo XML TTP.",
         "autodetect": "&Automaticky rozpoznat a zpracovat LandXML nebo XML TTP",
         "autodetect_tip": "Automaticky rozpozná, zda se jedná o LandXML soubor nebo XML TTP soubor",
         "toolbar": "Nástroje",
         "help": "Nápověda",
         "plots": "Grafy",
         "map": "Mapa",
         "view": "&Zobrazit",
         "mapSettings": "Nastavení mapy",
         "currentEPSG": "Souřadnicový systém LandXML na vstupu",
         "EPSGinfo": "Výstupní EPSG je vždy WGS-84 - EPSG:4326"

        },

     "en": {
        "open_file": "Open File (will open in LandXML tab)",
        "exit": "&Exit",
        "settings": "&Settings",
        "language": "&Language",
        "file": "&File",
        "color_mode": "Color Mode",
        "light": "Light",
        "dark": "Dark",
        "system": "System",
        "raw_data": "Raw Data",
        "parsed_data": "Parsed Data",
        "open_parse_landxml": "Open and Parse &LandXML",
        "open_parse_xmlttp": "Open and Parse XML &TTP",
        "cant_cant-def": "cant / cant deficiency [mm]",
         "cant": "cant [mm]",
        "station": "stationing [km]",
        "speed_lim": "speed limit [km/h]",
         "app_title": "COYPU - Clever Optimizer for Yielding of Potential and Utilization",
         "error": "Error",
         "no_file": "No file selected or error reading file.",
         "clean": "&Clean",
         "cleanTTP": "Clean &TTP data",
         "cleanLandXML": "Clean &LandXML data",
         "cleanAll": "&Clean all",
         "radius": "radius [m]",
         "curvature": "curvature [1/m]",
         "elevation": "elevation [m]",
         "select_sections_for_ttp_title": "Select Sections for TTP",
         "select_sections_for_ttp_description": "Select the sections you want to include in the TTP.",
         "crop_to_landxml": "Crop to LandXML data range",
         "unknown_xml_file": "Unknown XML file format. Expecting LandXML or XML TTP.",
         "autodetect": "&Autodetect and parse LandXML or XML TTP",
         "autodetect_tip": "Automatically detects whether it's a LandXML file or an XML TTP file",
         "toolbar": "Tools",
         "help": "Help",
         "plots": "Plots",
         "map": "Map",
         "view": "&View",
         "mapSettings": "Map Settings",
         "currentEPSG": "Input EPSG coordinate system of LandXML",
         "EPSGinfo": "Output EPSG is always WGS-84 - EPSG:4326"


         
        },  

     "de": {
        "open_file": "Datei öffnen (wird im LandXML-Tab geöffnet)",
        "exit": "&Beenden",
        "settings": "&Einstellungen",
        "language": "&Sprache",
        "file": "&Datei",
        "color_mode": "Farbmodus",
        "light": "Hell",
        "dark": "Dunkel",
        "system": "System",
        "raw_data": "Rohdaten",
        "parsed_data": "Verarbeitete Daten",
        "open_parse_landxml": "&LandXML öffnen und verarbeiten",
        "open_parse_xmlttp": "XML &TTP öffnen und verarbeiten",
        "cant_cant-def": "Überhöhung / Überhöhungfehlbetrag [mm]",
         "cant": "Überhöhung [mm]",
        "station": "Streckenkilometer [km]",
        "speed_lim": "Geschwindigkeitsbegrenzung [km/h]",
         "app_title": "COYPU - Clever Optimizer for Yielding of Potential and Utilization",
         "error": "Fehler",
         "no_file": "Kein Datei ausgewählt oder Fehler beim Lesen der Datei.",
         "clean": "Daten &löschen",
         "cleanTTP": "&TTP Daten löschen",
         "cleanLandXML": "&LandXML Daten löschen",
         "cleanAll": "Alle Daten &löschen",
         "radius": "Radius [m]",
         "curvature": "Krümmung [1/m]",
         "elevation": "Höhe [m]",
         "select_sections_for_ttp_title": "Abschnitte für TTP auswählen",
         "select_sections_for_ttp_description": "Wählen Sie die Abschnitte aus, die Sie in das TTP aufnehmen möchten.",
         "crop_to_landxml": "Auf LandXML-Datenbereich zuschneiden",
         "unknown_xml_file": "Unbekanntes XML-Dateiformat. Erwartet wird LandXML oder XML TTP.",
         "autodetect": "&LandXML oder XML TTP automatisch erkennen und verarbeiten",
         "autodetect_tip": "Automatisch erkennt, ob es sich um eine LandXML-Datei oder eine XML TTP-Datei handelt",
         "toolbar": "Werkzeuge",
         "help": "Hilfe",
         "plots": "Diagramme",
         "map": "Karte",
         "view": "&Anzeigen",
         "mapSettings": "Karteinstellungen",
         "currentEPSG": "Eingabe-EPSG-Koordinatensystem von LandXML",
         "EPSGinfo": "Ausgabe-EPSG ist immer WGS-84 - EPSG:4326"
        
        
        
        
        

        }
    }