# Languages for the UI


DIC = {
    "cz": {
        "open_file": "Otevřít soubor (otevře se v LandXML okně)",
        "exit": "&Ukončit",
        "settings": "&Nastavení",
        "language": "&Jazyk",
        "file": "&Soubor",
        "color_mode": "Motiv",
        "light": "Světlý",
        "dark": "Tmavý",
        "system": "Systémový",
        "raw_data": "Surová data",
        "parsed_data": "Zpracovaná data",
        "open_parse_landxml": "Otevřít a zpracovat &LandXML",
        "open_parse_xmlttp": "Otevřít a zpracovat XML &TTP",
        "cant_cant-def": "převýšení / nedostatek převýšení [mm]",
        "cant": "převýšení [mm]",
        "station": "staničení [km]",
        "speed_lim": "nejvyšší povolená rychlost [km/h]",
        "app_title": "COYPU - Clever Optimizer for Yielding of Potential and Utilization",
        "error": "Chyba",
        "no_file": "Nebyl vybrán žádný soubor nebo došlo k chybě při čtení souboru.",
        "clean": "&Vyčistit",
        "cleanTTP": "Vyčistit &TTP data",
        "cleanLandXML": "Vyčistit &LandXML data",
        "cleanAll": "Vyčistit &vše",
        "cleanCants": "Vyčistit vypočítané převýšení",
        "cleanSpeeds": "Vyčistit vypočítané rychlosti",
         "radius": "poloměr oblouku [m]",
         "curvature": "křivost [1/m]",
         "curvature_new": "nová křivost [1/m]",
         "elevation": "výška [m]",
         "select_sections_for_ttp_title": "Vyberte úsek",
         "select_sections_for_ttp_description": "Vyberte úseky, které chcete zahrnout do TTP.",
         "crop_to_landxml": "Oříznout na rozsah LandXML dat",
         "unknown_xml_file": "Neznámý formát XML souboru. Očekává se LandXML nebo XML TTP.",
         "autodetect": "&Automaticky rozpoznat a zpracovat LandXML nebo XML TTP",
         "autodetect_tip": "Automaticky rozpozná, zda se jedná o LandXML soubor nebo XML TTP soubor",
         "toolbar": "Nástroje",
         "help": "Nápověda",
         "plotsAlignment": "Grafy - Osa",
         "plotsProfile": "Grafy - Niveleta",
         "plotsKinematics": "Grafy - Jízdní doby",
         "map": "Mapa",
         "view": "&Zobrazit",
         "mapSettings": "Nastavení mapy",
         "currentEPSG": "Souřadnicový systém LandXML na vstupu",
         "EPSGinfo": "Výstupní EPSG je vždy WGS-84 - EPSG:4326",
         "calculate": "&Vypočítat",
         "calculate_geometry": "Vypočítat D, I a odpovídající rychlosti",
         "calculate_geometry_I":"Vypočítat I a odpovídající rychlosti, D se nemění",
         "calculate_train_speed": "Vypočítat rychlost vlaku",
         "geometry": "Geometrie",
         "train": "Jízda vlaku",
         "cant_possible": "možné převýšení [mm]",
         "cdef_100": "I100 [mm]",
         "cdef_130": "I130 [mm]",
         "cdef_150": "I150 [mm]",
         "cdef_K": "IK (Naklápěcí vlak) [mm]",
         "cant_def_100": "D + I100 [mm]",
         "cant_def_130": "D + I130 [mm]",
         "cant_def_150": "D + I150 [mm]",
         "cant_def_K": "D + IK (naklápěcí vlak) [mm]",
         "speed_lim_100": "V100 [km/h]",
         "speed_lim_130": "V130 [km/h]",
         "speed_lim_150": "V150 [km/h]",
         "speed_lim_K": "VK (Naklápěcí vlak) [km/h]",
         "load_all": "Načíst všechny úseky",
         "help_text": "Nápověda je dostupná v readme.md souboru",
         "standard_value": "Standardní hodnota",
         "limit_value": "Mezní hodnota",
         "maximum_value": "Maximální hodnota",
         "minimum_value": "Minimální hodnota",
         "cant_def": "Nedostatek převýšení I [mm]",
         "abrupt_cant_def": "Náhlá změna nedostatku převýšení deltaI [mm]",
         "geometrySettings": "Nastavení pro GPK",
         "vehicleSettings": "Nastavení parametrů vozidla",
         "Vbottom": "V_od [km/h]",
         "Vtop": "V_do [km/h]",
         "I_std": "I_std [mm]",
         "I_lim": "I_lim [mm]",
         "I_max": "I_max [mm]",
         "importCSV": "Načíst z CSV",
         "exportCSV": "Exportovat do CSV",
         "importError": "Chyba při importu",
         "dI_std": "dI_std [mm]",
         "dI_lim": "dI_lim [mm]",
         "dI_max": "dI_max [mm]",
         "nLin": "součinitel sklonu vzestupnice n [-]",
         "n_n": "n_n / V [-]",
         "n_n_abs": "n_n [-]",
         "n_lim": "n_lim / V [-]",
         "n_lim_abs": "n_lim [-]",
         "n_min": "n_min / V [-]",
         "n_min_abs": "n_min [-]",
         "nILin": "součinitel změny nedostatku převýšení nI [-]",
         "nI_n": "nI_n / V [-]",
         "nI_lim": "nI_lim / V [-]",
         "nI_min": "nI_min / V [-]",
         "designApproach": "Návrhový přístup",
         "designApproachLimitDescription": "Zvolte návrhový přístup (standardní, limitní, minimální/maximální hodnota)",
         "standard": "Standardní",
         "limit": "Limitní",
         "minmax": "Minimální/maximální",
         "cantNotFound": "Nebyla nalezena data o stávajícím převýšení.",
         "vehicleResistance": "Jízdní odpor vozidla",
         "vehicle": "Vozidlo",
         "coefA": "Koeficient A",
         "coefB": "Koeficient B",
         "coefC": "Koeficient C",
         "vehicleTraction": "Trakční parametry vozidla",
         "coef_b0": "Koeficient b0",
         "coef_b1": "Koeficient b1",
         "coef_b2": "Koeficient b2",
         "vehicleBrakeDyn": "Dynamická brzda vozidla",
         "vehicleBrakeMech": "Mechanická brzda vozidla [kN]:",
         "vehicleParam": "Parametry vozidla",
         "rotMass": "Součinitel rotující hmoty",
         "weight": "Hmotnost vozidla",
         "profile": "Niveleta",
         "elevation": "Nadmořská výška [m]",
         "report": "Výpis",
         "kinematicsSpeedLimitTrack": "Traťová rychlost - dráhový tachogram",
         "kinematicsSpeedLimitTime": "Traťová rychlost - časový tachogram",
         "speed": "Rychlost [km/h]",
         "speedM": "Rychlost [m/s]",
         "speedLimM": "Traťová rychlost [m/s]",
         "distance": "Vzdalenost [m]",
         "time": "Čas [s]",
         "max_train_speed": "Maximální rychlost vlaku [km/h]",
         "speed_profile": "Rychlostní profil pro jízdu",
         "speed_lim_ttp": "Traťová rychlost z TTP",
         "unlimited": "Neomezená rychlost",
         "kinematicsDistanceTime": "Vzdálenost - časový profil",
         "units_kmh": "Jednotky km/h a km (místo m/s a m)",
         "distanceKm": "Vzdálenost [km]",
         "timeMin": "Čas [min]",
         "speedKmh": "Rychlost [km/h]",
         "speedLimKmh": "Traťová rychlost [km/h]",
         "kinematicsForces": "Průběh sil",
         "forceTraction": "Trakční síla [kN]",
         "forceBraking": "Brzdná síla [kN]",
         "forceResistance": "Jízdní odpor [kN]",
         "forceKN": "Síla [kN]",
         "stopsSettings": "Nastavení zastávek",
         "importStopsTTP": "Importovat zastávky z XML TTP",
         "trainInitialSpeed": "Počáteční rychlost [km/h]",
         "trainFinalSpeed": "Koncová rychlost [km/h]",
         "defaultDwellTime": "Výchozí doba stání [s]",
         "trainStops": "Zastávky vlaku",
         "dwellTimeTable": "Doba stání [s]",
         "addRow": "Přidat řádek",
         "removeRow": "Odebrat řádek",
         "mapBase": "Mapový podklad:",
         "mapPositron": "CartoDB Positron",
         "mapOSM": "OpenStreetMap",
         "mapORM": "OpenRailwayMap",
         "mapCUZK": "ČÚZK Ortofoto"
         
         
        },

     "en": {
        "open_file": "Open File (will open in LandXML tab)",
        "exit": "&Exit",
        "settings": "&Settings",
        "language": "&Language",
        "file": "&File",
        "color_mode": "Color Mode",
        "light": "Light",
        "dark": "Dark",
        "system": "System",
        "raw_data": "Raw Data",
        "parsed_data": "Parsed Data",
        "open_parse_landxml": "Open and Parse &LandXML",
        "open_parse_xmlttp": "Open and Parse XML &TTP",
        "cant_cant-def": "cant / cant deficiency [mm]",
         "cant": "cant [mm]",
        "station": "stationing [km]",
        "speed_lim": "speed limit [km/h]",
         "app_title": "COYPU - Clever Optimizer for Yielding of Potential and Utilization",
         "error": "Error",
         "no_file": "No file selected or error reading file.",
         "clean": "&Clean",
         "cleanTTP": "Clean &TTP data",
         "cleanLandXML": "Clean &LandXML data",
         "cleanAll": "&Clean all",
         "cleanCants": "Clean calculated cants",
         "cleanSpeeds": "Clean calculated speeds",
         "radius": "radius [m]",
         "curvature": "curvature [1/m]",
         "curvature_new": "new curvature [1/m]",
         "elevation": "elevation [m]",
         "select_sections_for_ttp_title": "Select Sections for TTP",
         "select_sections_for_ttp_description": "Select the sections you want to include in the TTP.",
         "crop_to_landxml": "Crop to LandXML data range",
         "unknown_xml_file": "Unknown XML file format. Expecting LandXML or XML TTP.",
         "autodetect": "&Autodetect and parse LandXML or XML TTP",
         "autodetect_tip": "Automatically detects whether it's a LandXML file or an XML TTP file",
         "toolbar": "Tools",
         "help": "Help",
         "plotsAlignment": "Plots - Alignment",
         "plotsProfile": "Plots - Profile",
         "plotsKinematics": "Plots - Kinematics",
         "map": "Map",
         "view": "&View",
         "mapSettings": "Map Settings",
         "currentEPSG": "Input EPSG coordinate system of LandXML",
         "EPSGinfo": "Output EPSG is always WGS-84 - EPSG:4326",
         "calculate": "&Calculate",
         "calculate_geometry": "Calculate D, I and respective speeds",
         "calculate_geometry_I":"Calculate I and respective speeds, D stays the same",
         "calculate_train_speed": "Calculate train speed",
         "geometry": "Geometry",
         "train": "Train",
         "cant_possible": "possible cant [mm]",
         "cdef_100": "I100 [mm]",
         "cdef_130": "I130 [mm]",
         "cdef_150": "I150 [mm]",
         "cdef_K": "IK (tilting train) [mm]",
         "cant_def_100": "D + I100 [mm]",
         "cant_def_130": "D + I130 [mm]",
         "cant_def_150": "D + I150 [mm]",
         "cant_def_K": "D + IK (tilting train) [mm]",
         "speed_lim_100": "V100 [km/h]",
         "speed_lim_130": "V130 [km/h]",
         "speed_lim_150": "V150 [km/h]",
         "speed_lim_K": "VK (Tilting train) [km/h]",
         "load_all": "Load all sections",
         "help_text": "Help is available in readme.md file",
         "standard_value": "Standard Value",
         "limit_value": "Limit Value",
         "maximum_value": "Maximum Value",
         "minimum_value": "Minimum Value",
         "cant_def": "cant deficiency I [mm]",
         "abrupt_cant_def": "abrupt change of cant deficiency deltaI [mm]",
         "geometrySettings": "Track Geometry Settings",
         "vehicleSettings": "Vehicle Settings",
         "Vbottom": "V_from [km/h]",
         "Vtop": "V_to [km/h]",
         "I_std": "I_std [mm]",
         "I_lim": "I_lim [mm]",
         "I_max": "I_max [mm]",
         "importCSV": "Import from CSV",
         "exportCSV": "Export to CSV",
         "importError": "Error importing",
         "dI_std": "dI_std [mm]",
         "dI_lim": "dI_lim [mm]",
         "dI_max": "dI_max [mm]",
         "nLin": "cant ramp gradient n [-]",
         "n_n": "n_n / V [-]",
         "n_n_abs": "n_n [-]",
         "n_lim": "n_lim / V [-]",
         "n_lim_abs": "n_lim [-]",
         "n_min": "n_min / V [-]",
         "n_min_abs": "n_min [-]",
         "nILin": "Coefficient of cant deficiency change nI [-]",
         "nI_n": "nI_n / V [-]",
         "nI_lim": "nI_lim / V [-]",
         "nI_min": "nI_min / V [-]",
         "designApproach": "Design Approach",
         "designApproachLimitDescription": "Select design approach (standard, limit, minimum/maximum value)",
         "standard": "Standard",
         "limit": "Limit",
         "minmax": "Min/Max",
         "cantNotFound": "Cant deficiency data not found.",
         "vehicleResistance": "Vehicle Resistance",
         "vehicle": "Vehicle",
         "coefA": "Coefficient A",
         "coefB": "Coefficient B",
         "coefC": "Coefficient C",
         "vehicleTraction": "Vehicle Traction",
         "coef_b0": "Coefficient b0",
         "coef_b1": "Coefficient b1",
         "coef_b2": "Coefficient b2",
         "vehicleBrakeDyn": "Vehicle Dynamic Braking",
         "vehicleBrakeMech": "Mechanical Braking [kN]:",
         "vehicleParam": "Vehicle Parameters",
         "rotMass": "Rotation Mass Coefficient",
         "weight": "Vehicle Weight",
         "profile": "Profile",
         "elevation": "Elevation [m]",
         "report": "Report",
         "kinematicsSpeedLimitTrack": "Speed Limit - Velocity-Distance Profile",
         "kinematicsSpeedLimitTime": "Speed Limit - Velocity-Time Profile",
         "speed": "Speed [km/h]",
         "speedM": "Speed [m/s]",
         "speedLimM": "Speed Limit [m/s]",
         "distance": "Distance [m]",
         "time": "Time [s]",
         "max_train_speed": "Max Train Speed [km/h]",
         "speed_profile": "Speed Profile",
         "speed_lim_ttp": "TTP Speed Limits",
         "unlimited": "Unlimited Speed",
         "kinematicsDistanceTime": "Distance - Time Profile",
         "units_kmh": "Units in km/h and km (instead of m/s and m)",
         "distanceKm": "Distance [km]",
         "timeMin": "Time [min]",
         "speedKmh": "Speed [km/h]",
         "speedLimKmh": "Speed Limit [km/h]",
         "kinematicsForces": "Forces Profile",
         "forceTraction": "Tractive Force [kN]",
         "forceBraking": "Braking Force [kN]",
         "forceResistance": "Resistance [kN]",
         "forceKN": "Force [kN]",
         "stopsSettings": "Stops Settings",
         "importStopsTTP": "Import Stops from XML TTP",
         "trainInitialSpeed": "Initial Speed [km/h]",
         "trainFinalSpeed": "Final Speed [km/h]",
         "defaultDwellTime": "Default Dwell Time [s]",
         "trainStops": "Train Stops",
         "dwellTimeTable": "Dwell Time [s]",
         "addRow": "Add Row",
         "removeRow": "Remove Row",
         "mapBase": "Base Map:",
         "mapPositron": "CartoDB Positron",
         "mapOSM": "OpenStreetMap",
         "mapORM": "OpenRailwayMap",
         "mapCUZK": "ČÚZK Orthophoto"
         
         
         
         
        },  

     "de": {
        "open_file": "Datei öffnen (wird im LandXML-Tab geöffnet)",
        "exit": "&Beenden",
        "settings": "&Einstellungen",
        "language": "&Sprache",
        "file": "&Datei",
        "color_mode": "Farbmodus",
        "light": "Hell",
        "dark": "Dunkel",
        "system": "System",
        "raw_data": "Rohdaten",
        "parsed_data": "Verarbeitete Daten",
        "open_parse_landxml": "&LandXML öffnen und verarbeiten",
        "open_parse_xmlttp": "XML &TTP öffnen und verarbeiten",
        "cant_cant-def": "Überhöhung / Überhöhungfehlbetrag [mm]",
         "cant": "Überhöhung [mm]",
        "station": "Streckenkilometer [km]",
        "speed_lim": "Geschwindigkeitsbegrenzung [km/h]",
         "app_title": "COYPU - Clever Optimizer for Yielding of Potential and Utilization",
         "error": "Fehler",
         "no_file": "Kein Datei ausgewählt oder Fehler beim Lesen der Datei.",
         "clean": "Daten &löschen",
         "cleanTTP": "&TTP Daten löschen",
         "cleanLandXML": "&LandXML Daten löschen",
         "cleanAll": "Alle Daten &löschen",
         "cleanCants": "Berechnete Überhöhung löschen",
         "cleanSpeeds": "Berechnete Geschwindigkeiten löschen",
         "radius": "Radius [m]",
         "curvature": "Krümmung [1/m]",
         "curvature_new": "neue Krümmung [1/m]",
         "elevation": "Höhe [m]",
         "select_sections_for_ttp_title": "Abschnitte für TTP auswählen",
         "select_sections_for_ttp_description": "Wählen Sie die Abschnitte aus, die Sie in das TTP aufnehmen möchten.",
         "crop_to_landxml": "Auf LandXML-Datenbereich zuschneiden",
         "unknown_xml_file": "Unbekanntes XML-Dateiformat. Erwartet wird LandXML oder XML TTP.",
         "autodetect": "&LandXML oder XML TTP automatisch erkennen und verarbeiten",
         "autodetect_tip": "Automatisch erkennt, ob es sich um eine LandXML-Datei oder eine XML TTP-Datei handelt",
         "toolbar": "Werkzeuge",
         "help": "Hilfe",
         "plotsAlignment": "Diagramme - hor. Trassierung",
         "plotsProfile": "Diagramme - vert. Trassierung",
         "plotsKinematics": "Diagramme - Fahrtverlauf",
         "map": "Karte",
         "view": "&Anzeigen",
         "mapSettings": "Karteinstellungen",
         "currentEPSG": "Eingabe-EPSG-Koordinatensystem von LandXML",
         "EPSGinfo": "Ausgabe-EPSG ist immer WGS-84 - EPSG:4326",
         "calculate": "&Berechnen",
         "calculate_geometry": "Berechnen u, u_f und Geschwindigkeiten",
         "calculate_geometry_I":"Berechnen u_f und Geschwindigkeiten, u ist nicht geändert",
         "calculate_train_speed": "Berechnen Zuggeschwindigkeit",
         "geometry": "Geometrie",
         "train": "Zugfahrt",
         "cant_possible": "Mögliche Überhöhung [mm]",
         "cdef_100": "u_f100 [mm]",
         "cdef_130": "u_f130 [mm]",
         "cdef_150": "u_f150 [mm]",
         "cdef_K": "u_fK (Neigezug) [mm]",
         "cant_def_100": "u + u_f100 [mm]",
         "cant_def_130": "u + u_f130 [mm]",
         "cant_def_150": "u + u_f150 [mm]",
         "cant_def_K": "u + u_fK (Neigezug) [mm]",
         "speed_lim_100": "V100 [km/h]",
         "speed_lim_130": "V130 [km/h]",
         "speed_lim_150": "V150 [km/h]",
         "speed_lim_K": "VK (Neigezug) [km/h]",
         "load_all": "Alle Abschnitte laden",
         "help_text": "Hilfe ist im readme.md-Datei verfügbar",
         "standard_value": "Standardwert",
         "limit_value": "Grenzenwert",
         "maximum_value": "Maximalwert",
         "minimum_value": "Minimalwert",
         "cant_def": "Überhöhungsgsfehlbetrag I [mm]",
         "abrupt_cant_def": "abrupte Überhöhungsgsfehlbetragänderung deltaI [mm]",
         "geometrySettings": "Einstellungen der Gleislage",
         "vehicleSettings": "Fahrzeug-Einstellungen",
         "Vbottom": "V_von [km/h]",
         "Vtop": "V_bis [km/h]",
         "I_std": "I_std [mm]",
         "I_lim": "I_lim [mm]",
         "I_max": "I_max [mm]",
         "importCSV": "CSV-Datei importieren",
         "exportCSV": "CSV-Datei exportieren",
         "importError": "Fehler beim Importieren",
         "dI_std": "dI_std [mm]",
         "dI_lim": "dI_lim [mm]",
         "dI_max": "dI_max [mm]",
         "nLin": "Neigung der Überhöhungsrampe n [-]",
         "n_n": "n_n / V [-]",
         "n_n_abs": "n_n [-]",
         "n_lim": "n_lim / V [-]",
         "n_lim_abs": "n_lim [-]",
         "n_min": "n_min / V [-]",
         "n_min_abs": "n_min [-]",
         "nILin": "Koeffizient der Überhöhungsfehlbetragsänderung nI [-]",
         "nI_n": "nI_n / V [-]",
         "nI_lim": "nI_lim / V [-]",
         "nI_min": "nI_min / V [-]",
         "designApproach": "Entwurfsmöglichkeit",
         "designApproachLimitDescription": "Wählen Sie Entwurfsmöglichkeit aus (Standardwert, Limitwert, Maximal-/Minimalwert).",
         "standard": "Standard",
         "limit": "Limit",
         "minmax": "Min/Max",
         "cantNotFound": "Überhöhungsg Daten nicht gefunden.",
         "vehicleResistance": "Fahrzeugwiderstand",
         "vehicle": "Fahrzeug",
         "coefA": "Koeffizient A",
         "coefB": "Koeffizient B",
         "coefC": "Koeffizient C",
         "vehicleTraction": "Fahrzeugtraktionsparameter",
         "coef_b0": "Koeffizient b0",
         "coef_b1": "Koeffizient b1",
         "coef_b2": "Koeffizient b2",
         "vehicleBrakeDyn": "Dynamische Bremse",
         "vehicleBrakeMech": "Mechanische Bremse [kN]:",
         "vehicleParam": "Fahrzeugparameter",
         "rotMass": "Drehmomentkoeffizient",
         "weight": "Fahrzeuggewicht",
         "profile": "Nivelette",
         "elevation": "Höhe [m]",
         "report": "Bericht",
         "kinematicsSpeedLimitTrack": "Höchstgeschwindigkeit - v - s Diagramm",
         "kinematicsSpeedLimitTime": "Speed Limit - v - t Diagramm",
         "speed": "Geschwindigkeit [km/h]",
         "speedM": "Geschwindigkeit [m/s]",
         "speedLimM": "Höchstgeschwindigkeit [m/s]",
         "distance": "Distanz [m]",
         "time": "Zeit [s]",
         "max_train_speed": "Maximale Zuggeschwindigkeit [km/h]",
         "speed_profile": "Geschwindigkeitsprofil",
         "speed_lim_ttp": "TTP Geschwindigkeitsgrenzen",
         "unlimited": "Unbegrenzte Geschwindigkeit",
         "kinematicsDistanceTime": "Weg-Zeit-Diagramm",
         "units_kmh": "Einheiten in km/h und km (statt m/s und m)",
         "distanceKm": "Distanz [km]",
         "timeMin": "Zeit [min]",
         "speedKmh": "Geschwindigkeit [km/h]",
         "speedLimKmh": "Höchstgeschwindigkeit [km/h]",
         "kinematicsForces": "Kräfteverlauf",
         "forceTraction": "Zugkraft [kN]",
         "forceBraking": "Bremskraft [kN]",
         "forceResistance": "Widerstand [kN]",
         "forceKN": "Kraft [kN]",
         "stopsSettings": "Halteeinstellungen",
         "importStopsTTP": "Halte aus XML TTP importieren",
         "trainInitialSpeed": "Anfangsgeschwindigkeit [km/h]",
         "trainFinalSpeed": "Endgeschwindigkeit [km/h]",
         "defaultDwellTime": "Standardhaltezeit [s]",
         "trainStops": "Zughalte",
         "dwellTimeTable": "Haltezeit [s]",
         "addRow": "Zeile hinzufügen",
         "removeRow": "Zeile entfernen",
         "mapBase": "Kartengrundlage:",
         "mapPositron": "CartoDB Positron",
         "mapOSM": "OpenStreetMap",
         "mapORM": "OpenRailwayMap",
         "mapCUZK": "ČÚZK Orthofoto"
         
        
        }
    }